version: '3'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=${DOCKER_PHP_VERSION}
        - NODE_VERSION=${DOCKER_NODE_VERSION}
        - CONTAINER_SRC_ROOT=${DOCKER_CONTAINER_SRC_ROOT}
    volumes:
    - .:${DOCKER_CONTAINER_SRC_ROOT}:cached

  nginx:
    image: nginx:${DOCKER_NGINX_VERSION}
    container_name: nginx
    environment:
      - DOMAIN=${DOCKER_DOMAIN}
      - DOCUMENT_ROOT=${DOCKER_CONTAINER_SRC_ROOT}/public
      - HTTP_PORT=${DOCKER_HTTP_PORT}
      - HTTPS_PORT=${DOCKER_HTTPS_PORT}
    command: >
      /bin/sh -c
      "envsubst '
      $$DOCUMENT_ROOT
      $$DOMAIN
      $$HTTP_PORT
      $$HTTPS_PORT
      '< /etc/nginx/conf.d/default.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    ports:
      - '${DOCKER_HTTP_PORT}:80'
      - '${DOCKER_HTTPS_PORT}:443'
    volumes:
      - .:${DOCKER_CONTAINER_SRC_ROOT}:cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - php

  db:
    image: mysql:${DOCKER_MYSQL_VERSION}
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306